### ISSUE TITLE
Various user experience things

### ISSUE THREAD

**Issue by elliot-forty-two** [platky/PkmnIssues#5]
* No close/cancel button on login/register dialogs
* Clickable table rows should use the hand cursor to indicate they invoke navigation
* Card image popup shows the previously loaded image when hovering over a different row until the new image is loaded, which can take a while

**Comment by elliot-forty-two** [comment]
Resizing the browser window to tablet and phone sizes triggers responsive layout changes everywhere but the table of sets/cards, up to half the table spills out to the right. You could maybe cut some columns in mobile views, or wrap the owned count spinners to the next line?

**Comment by platky** [comment]
- Windows are currently close-able by clicking anywhere off of them but I will add an additional close button onto them
- Definitely was needed, done!
- This should be working correctly now, I will have to test further on a slower connection

- Some of the less important columns get cut out now as you suggested. I have dedicated mobile applications in progress but for now I think this should work out. Base Set is still wonky because of the four different types, I will have to adjust further.

Thanks for all of the suggestions and input so far!
